{
  "hash": "d7ee8da5ee62cee9b12e05fb9d5137e2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"stat_modelling\"\neditor: visual\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n# 1.0 Introduction\n\nIn this project we will be using a subset of the data from the Behavioral Risk Factor Surveillance System (BRFSS) from the CDC to investigate possible risk factors for arthritis. The BRFSS is a system of health-related telephone surveys that collect state data about U.S. residents regarding their health-related risk behaviors, chronic health conditions, and use of preventive services. It was established in 1984 with 15 states, BRFSS now collects data in all 50 states. This dataset contains health and social information about non-institutionalized adults in the US in 2013. There are 359,925 individuals included (rows) and 16 variables (columns). The goal is of the study is to investigate risk factors associated with arthritis.\n\n\n\n\n\n\n\n\n\n# Data preparation\n\nTo prepare the dataset for analysis, we used a variety of functions to explore its structure, variability, and completeness. The map_df() function was used to check the number of unique values for each variable, dim() to confirm the dimensions (359,925 rows, and 16 columns), and the summary() function was used to obtain summary statistics.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmap_df(df_brfss,n_distinct)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 16\n  fruits veggies   age under30 age30to64 age65plus arthritis female genhealth\n   <int>   <int> <int>   <int>     <int>     <int>     <int>  <int>     <int>\n1     10      10    13       2         2         2         2      2         5\n# ℹ 7 more variables: education <int>, income <int>, active <int>,\n#   active1 <int>, bmi <int>, bmicat <int>, activetimes <int>\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_brfss |> \n  dim() # checking dimensions of the dataset\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 359925     16\n```\n\n\n:::\n:::\n\n\n\n\nThe dataset has 359,925 rows, and 16 columns\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_brfss |> \n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     fruits          veggies           age            under30      \n Min.   :0.0000   Min.   :0.000   Min.   : 1.000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.000   1st Qu.: 5.000   1st Qu.:0.0000  \n Median :1.0000   Median :1.000   Median : 8.000   Median :0.0000  \n Mean   :0.9969   Mean   :0.805   Mean   : 7.495   Mean   :0.0949  \n 3rd Qu.:1.0000   3rd Qu.:1.000   3rd Qu.:10.000   3rd Qu.:0.0000  \n Max.   :9.0000   Max.   :9.000   Max.   :13.000   Max.   :1.0000  \n   age30to64        age65plus        arthritis          female      \n Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  \n Median :1.0000   Median :0.0000   Median :0.0000   Median :1.0000  \n Mean   :0.6004   Mean   :0.3047   Mean   :0.3336   Mean   :0.5679  \n 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  \n   genhealth       education         income          active      \n Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :0.0000  \n 1st Qu.:2.000   1st Qu.:4.000   1st Qu.:4.000   1st Qu.:0.0000  \n Median :2.000   Median :5.000   Median :6.000   Median :1.0000  \n Mean   :2.536   Mean   :4.935   Mean   :5.674   Mean   :0.7388  \n 3rd Qu.:3.000   3rd Qu.:6.000   3rd Qu.:8.000   3rd Qu.:1.0000  \n Max.   :5.000   Max.   :6.000   Max.   :8.000   Max.   :1.0000  \n    active1          bmi            bmicat       activetimes    \n Min.   :0.00   Min.   :12.02   Min.   :1.000   Min.   :  0.00  \n 1st Qu.:0.00   1st Qu.:23.75   1st Qu.:2.000   1st Qu.:  0.00  \n Median :1.00   Median :26.96   Median :3.000   Median : 12.00  \n Mean   :0.94   Mean   :27.97   Mean   :2.942   Mean   : 11.83  \n 3rd Qu.:1.00   3rd Qu.:30.99   3rd Qu.:4.000   3rd Qu.: 20.00  \n Max.   :2.00   Max.   :93.55   Max.   :4.000   Max.   :396.00  \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_brfss |> \n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 16\n  fruits veggies   age under30 age30to64 age65plus arthritis female genhealth\n   <dbl>   <dbl> <dbl>   <dbl>     <dbl>     <dbl>     <dbl>  <dbl>     <dbl>\n1      0       0     7       0         1         0         0      1         3\n2      0       1     8       0         1         0         1      1         3\n3      0       1     9       0         1         0         0      1         2\n4      0       1    10       0         0         1         0      0         3\n5      1       1     6       0         1         0         0      1         2\n6      1       1     7       0         1         0         1      0         1\n# ℹ 7 more variables: education <dbl>, income <dbl>, active <dbl>,\n#   active1 <dbl>, bmi <dbl>, bmicat <dbl>, activetimes <dbl>\n```\n\n\n:::\n:::\n\n\n\n\nIn the code below we are going to subset the dataset to include the following variables of importance:\n\n\\- Arthritis\n\n\\- Physical activity\n\n\\- BMI\n\n\\- Age(65 or over)\n\n - Sex\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sub-setting and inspecting the dataset\nlean_brfss<-df_brfss |> \n  select(arthritis,female,age65plus,active,bmi) |> \n  mutate(arthritis=factor(if_else(arthritis==1,\"Yes\",\"No\"),\n                          levels = c(\"Yes\",\"No\")),\n         age_65_or_over=factor(if_else(age65plus==1,\"Yes\",\"No\"),\n                               levels = c(\"Yes\",\"No\")),\n         Sex=factor(if_else(female==1,\"Female\",\"Male\"),levels = c(\"Female\",\"Male\")),\n         physical_activity=factor(if_else(active==1,\"Yes\",\"No\"))) |> \n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 359,925\nColumns: 8\n$ arthritis         <fct> No, Yes, No, No, No, Yes, No, No, Yes, No, Yes, No, …\n$ female            <dbl> 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0…\n$ age65plus         <dbl> 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0…\n$ active            <dbl> 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1…\n$ bmi               <dbl> 18.22, 27.46, 21.97, 35.94, 39.86, 30.17, 28.29, 29.…\n$ age_65_or_over    <fct> No, No, No, Yes, No, No, Yes, No, No, Yes, Yes, No, …\n$ Sex               <fct> Female, Female, Female, Male, Female, Male, Female, …\n$ physical_activity <fct> Yes, No, Yes, No, Yes, Yes, Yes, Yes, No, No, Yes, Y…\n```\n\n\n:::\n:::\n\n\n\n\n# Exploratory Data Analysis\n\nIn this section we will conduct an exploratory data analysis which is a way of investigating and understanding the structure of our data. To do this I used a range of graphical, and numerical methods including means, histograms, Q-Q plots, and contingency tables. Histograms have been selected because they clearly show the distribution of data (bmi in this case) and provide a quick perspective of whether or not data is skewed. Since one graphical method is rarely sufficient, Q-Q plots have been used to add a further perspective in assessing the normality of the data. Finally, Boxplots will also be used as they conspicuously indicate whether or not we have outliers in a dataset.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlean_brfss |> \n  is.na() |> \n  sum()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n\nThe dataset does not have missing values as the sum of all missing values is zero.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlean_brfss %>% \n  ggplot(aes(x = arthritis, fill = arthritis))+\n  geom_bar(aes(y = after_stat(count/sum(count))), stat = \"count\") +\n  theme_bw() +\n  labs(title = \"Arthritis prevalence\",\n       x = \"Arthritis Status\",\n       y = \"Proportion\",\n       fill = \"Arthritis\") +\n   scale_y_continuous(labels = scales::percent_format(scale = 100))\n```\n\n::: {.cell-output-display}\n![](stat_modelling_files/figure-html/Distribution of the target variable-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlean_brfss |> \n  ggplot(aes(x = bmi)) +\n  geom_boxplot(aes(),color = \"steelblue\") +\n  coord_flip() +\n  #facet_grid(~arthritis)+\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](stat_modelling_files/figure-html/Checking for Outliers-1.png){width=672}\n:::\n:::\n\n\n\n\nSeeing from the output, the variable bmi, has significant outliers which could affected the analysis, and result in biased outputs. In the subsequent section, we are going to remove outliers.\n\n## Removing outliers\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nQ <- quantile(lean_brfss$bmi, probs=c(.25, .75), na.rm = FALSE) # Specifying the lower and upper quatiles\niqr <- IQR(lean_brfss$bmi) # Interquatile range\nup <-  Q[2]+1.5*iqr # Upper Range  \nlow<- Q[1]-1.5*iqr # Lower Range\nbrfss_eliminated<- subset(lean_brfss, lean_brfss$bmi > (Q[1] - 1.5*iqr) & lean_brfss$bmi < (Q[2]+1.5*iqr))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwith_outliers<-lean_brfss |> \n  ggplot(aes(x = bmi)) +\n  geom_boxplot(aes(),color = \"steelblue\") +\n  coord_flip() +\n  #facet_grid(~arthritis)+\n  theme_bw() +\n  labs(title = \"With outliers\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwithout_outliers<-brfss_eliminated |> \n  ggplot(aes(x = bmi)) +\n  geom_boxplot(aes(),color = \"steelblue\") +\n  coord_flip() +\n  #facet_grid(~arthritis)+\n  theme_bw() +\n  labs(title = \"Without outliers\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncowplot::plot_grid(with_outliers, without_outliers)\n```\n\n::: {.cell-output-display}\n![](stat_modelling_files/figure-html/Comparing with and without outliers-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbrfss_eliminated |> \n  ggplot(aes(x = bmi))+\n  geom_histogram(aes(y = after_stat(density), fill = ..count..),bins = 30)+\n  facet_grid(~arthritis) +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.\nℹ Please use `after_stat(count)` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stat_modelling_files/figure-html/Histogram for BMI-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsex_subt<-brfss_eliminated |> \n  select(Sex,arthritis)\n\nactivity_subt<-brfss_eliminated |> \n  select(physical_activity,arthritis)\n\nage_subt<-brfss_eliminated |> \n  select(age_65_or_over,arthritis)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsex_subt |> \n  tbl_cross(row = Sex,\n            col = arthritis,\n            percent = \"column\") |> \n  bold_labels()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"laxcjekogx\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#laxcjekogx table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#laxcjekogx thead, #laxcjekogx tbody, #laxcjekogx tfoot, #laxcjekogx tr, #laxcjekogx td, #laxcjekogx th {\n  border-style: none;\n}\n\n#laxcjekogx p {\n  margin: 0;\n  padding: 0;\n}\n\n#laxcjekogx .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#laxcjekogx .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#laxcjekogx .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#laxcjekogx .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#laxcjekogx .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#laxcjekogx .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#laxcjekogx .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#laxcjekogx .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#laxcjekogx .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#laxcjekogx .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#laxcjekogx .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#laxcjekogx .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#laxcjekogx .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#laxcjekogx .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#laxcjekogx .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#laxcjekogx .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#laxcjekogx .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#laxcjekogx .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#laxcjekogx .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#laxcjekogx .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#laxcjekogx .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#laxcjekogx .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#laxcjekogx .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#laxcjekogx .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#laxcjekogx .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#laxcjekogx .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#laxcjekogx .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#laxcjekogx .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#laxcjekogx .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#laxcjekogx .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#laxcjekogx .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#laxcjekogx .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#laxcjekogx .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#laxcjekogx .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#laxcjekogx .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#laxcjekogx .gt_left {\n  text-align: left;\n}\n\n#laxcjekogx .gt_center {\n  text-align: center;\n}\n\n#laxcjekogx .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#laxcjekogx .gt_font_normal {\n  font-weight: normal;\n}\n\n#laxcjekogx .gt_font_bold {\n  font-weight: bold;\n}\n\n#laxcjekogx .gt_font_italic {\n  font-style: italic;\n}\n\n#laxcjekogx .gt_super {\n  font-size: 65%;\n}\n\n#laxcjekogx .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#laxcjekogx .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#laxcjekogx .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#laxcjekogx .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#laxcjekogx .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#laxcjekogx .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#laxcjekogx .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#laxcjekogx .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#laxcjekogx div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"label\"></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"level 1; stat_1\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KiphcnRocml0aXMqKg==\"><span class='gt_from_md'><strong>arthritis</strong></span></span></div>\n      </th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"KipUb3RhbCoq\"><span class='gt_from_md'><strong>Total</strong></span></span></th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"WWVz\"><span class='gt_from_md'>Yes</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"Tm8=\"><span class='gt_from_md'>No</span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Sex</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">71,737 (63%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">124,693 (53%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">196,430 (56%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">42,144 (37%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">109,887 (47%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">152,031 (44%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Total</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">113,881 (100%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">234,580 (100%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">348,461 (100%)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nactivity_subt |> \n  tbl_cross(row = physical_activity,\n            col = arthritis,\n            percent = \"column\") |> \n  bold_labels()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lsljofelrj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lsljofelrj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lsljofelrj thead, #lsljofelrj tbody, #lsljofelrj tfoot, #lsljofelrj tr, #lsljofelrj td, #lsljofelrj th {\n  border-style: none;\n}\n\n#lsljofelrj p {\n  margin: 0;\n  padding: 0;\n}\n\n#lsljofelrj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lsljofelrj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lsljofelrj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lsljofelrj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lsljofelrj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lsljofelrj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lsljofelrj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lsljofelrj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lsljofelrj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lsljofelrj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lsljofelrj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lsljofelrj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lsljofelrj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lsljofelrj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lsljofelrj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lsljofelrj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lsljofelrj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lsljofelrj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lsljofelrj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lsljofelrj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lsljofelrj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lsljofelrj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lsljofelrj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lsljofelrj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lsljofelrj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lsljofelrj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lsljofelrj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lsljofelrj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lsljofelrj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lsljofelrj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lsljofelrj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lsljofelrj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lsljofelrj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lsljofelrj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lsljofelrj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lsljofelrj .gt_left {\n  text-align: left;\n}\n\n#lsljofelrj .gt_center {\n  text-align: center;\n}\n\n#lsljofelrj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lsljofelrj .gt_font_normal {\n  font-weight: normal;\n}\n\n#lsljofelrj .gt_font_bold {\n  font-weight: bold;\n}\n\n#lsljofelrj .gt_font_italic {\n  font-style: italic;\n}\n\n#lsljofelrj .gt_super {\n  font-size: 65%;\n}\n\n#lsljofelrj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lsljofelrj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lsljofelrj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lsljofelrj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lsljofelrj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lsljofelrj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lsljofelrj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#lsljofelrj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#lsljofelrj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"label\"></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"level 1; stat_1\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KiphcnRocml0aXMqKg==\"><span class='gt_from_md'><strong>arthritis</strong></span></span></div>\n      </th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"KipUb3RhbCoq\"><span class='gt_from_md'><strong>Total</strong></span></span></th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"WWVz\"><span class='gt_from_md'>Yes</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"Tm8=\"><span class='gt_from_md'>No</span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">physical_activity</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    No</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">36,915 (32%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">51,544 (22%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">88,459 (25%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Yes</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">76,966 (68%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">183,036 (78%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">260,002 (75%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Total</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">113,881 (100%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">234,580 (100%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">348,461 (100%)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nage_subt |> \n  tbl_cross(row = age_65_or_over,\n            col = arthritis,\n            percent = \"column\") |> \n  bold_labels()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"nawagiukdj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nawagiukdj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nawagiukdj thead, #nawagiukdj tbody, #nawagiukdj tfoot, #nawagiukdj tr, #nawagiukdj td, #nawagiukdj th {\n  border-style: none;\n}\n\n#nawagiukdj p {\n  margin: 0;\n  padding: 0;\n}\n\n#nawagiukdj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nawagiukdj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nawagiukdj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nawagiukdj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nawagiukdj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nawagiukdj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nawagiukdj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nawagiukdj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nawagiukdj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nawagiukdj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nawagiukdj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nawagiukdj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nawagiukdj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nawagiukdj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nawagiukdj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nawagiukdj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nawagiukdj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nawagiukdj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nawagiukdj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nawagiukdj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nawagiukdj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nawagiukdj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nawagiukdj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nawagiukdj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nawagiukdj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nawagiukdj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nawagiukdj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nawagiukdj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nawagiukdj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nawagiukdj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nawagiukdj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nawagiukdj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nawagiukdj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nawagiukdj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nawagiukdj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nawagiukdj .gt_left {\n  text-align: left;\n}\n\n#nawagiukdj .gt_center {\n  text-align: center;\n}\n\n#nawagiukdj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nawagiukdj .gt_font_normal {\n  font-weight: normal;\n}\n\n#nawagiukdj .gt_font_bold {\n  font-weight: bold;\n}\n\n#nawagiukdj .gt_font_italic {\n  font-style: italic;\n}\n\n#nawagiukdj .gt_super {\n  font-size: 65%;\n}\n\n#nawagiukdj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nawagiukdj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nawagiukdj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nawagiukdj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nawagiukdj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nawagiukdj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nawagiukdj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#nawagiukdj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#nawagiukdj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"label\"></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"level 1; stat_1\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KiphcnRocml0aXMqKg==\"><span class='gt_from_md'><strong>arthritis</strong></span></span></div>\n      </th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"KipUb3RhbCoq\"><span class='gt_from_md'><strong>Total</strong></span></span></th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"WWVz\"><span class='gt_from_md'>Yes</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"Tm8=\"><span class='gt_from_md'>No</span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">age_65_or_over</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Yes</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">56,240 (49%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">51,271 (22%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">107,511 (31%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    No</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">57,641 (51%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">183,309 (78%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">240,950 (69%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Total</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">113,881 (100%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">234,580 (100%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">348,461 (100%)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbrfss_eliminated %>% \n  count(Sex, arthritis) %>%\n  ggplot(aes(x = Sex, \n             y = arthritis)) +\n  geom_tile(aes(fill=n)) +\n  labs(x = \"Sex\",\n       y = \"Arthritis\",\n       fill = \"Count\") +\n  scale_fill_distiller(palette = \"RdPu\") +\n  theme_classic(base_size = 16)\n```\n\n::: {.cell-output-display}\n![](stat_modelling_files/figure-html/Arthritis and Sex Tile plot-1.png){width=672}\n:::\n:::\n\n\n\n\n## Observations\n\nThe box plots show higher median BMI in the arthritis group with just fewer outliers after filtering. Histograms show a right skewed distribution where as contingency tables suggest higher arthritis prevalence among females (63%), those aged 65 or over (49% vs 22%), and those with no physical activity. the distribution of BMI as a variable indicates skewness and presence of outliers. This variables will be transformed prior to analysis.\n\n# Analysis plan\n\nThe analysis aims to investigate and quantify associations between arthritis (Yes/No) and risk factors: Sex (Female, Male), age (Less or More than 65), physical activity (Yes/No), and BMI. We will use both descriptive, and inferential methods to address the research questions. Descriptive statistics will be used as they are appropriate for generating summary statistics (means, medians) which will be useful in identifying preliminary patterns.\n\nChi square tests will be performed to assess the association between arthritis and each categorical variable (physical exercise, sex, age category).\n\nWe will also employ t tests or Wilcoxon Rank Sum test (depending on normality) to compare the means of BMI for those that have arthritis, and those that do not.BMI is numeric and continuous variable, and arthritis is a categorical variable, requiring a a two group comparison, and this makes t-tests or Wilcoxon Rank Sum Test a method of choice.\n\nWe will also calculate the relative risk ratio to assess the relative risk of having arthritis depending on the sex, age, and physical activity of an individual. Relative Risk is preferred over odds ration in this case due to direct interpretation as a risk.\n\nFinally, we will run a logistic regression model to understand the collective relative risk of sex, age, physical activity, BMI, on the target variable (arthritis).\n\n## Data dictionary\n\n-   Arthritis: A binary outcome variable taking the values of Yes(1), and No(2).\n-   Physical activity: A binary explanatory variable taking the values of Yes(1), or No(2) to indicate whether an individual is exercising or not respectively.\n-   Age 65 or over: A binary explanatory variable taking the values of Yes(1), or No(2) to indicate whether or not the individual is above or below 65 years of age respectively.\n-   Sex: A binary explanatory variable taking the values of Female(1), or Male(2) to indicate whether or not the individual is Female or Male respectively.\n-   BMI: A numeric continuous variable showing the Body Mass Index (BMI) for an individual.\n\n# Hypothesis\n\nIn our analysis we are going to make the following hypotheses: \\## Chi-square tests. - Null: There is no association between arthritis, and Sex of an individual. - Alternative: There is an association between arthritis, and Sex of an individual.\n\n-   Null: There is no association between arthritis, and physical activity of an individual.\n\n-   Alternative: There is an association between arthritis, and physical activity of an individual.\n\n-   Null: There is no association between arthritis, and of an individual.\n\n-   Alternative: There is an association between arthritis, and Sex of an individual.\n\n-   Null: There is no association between arthritis, and age catagory (65 or over) of an individual.\n\n-   Alternative: There is an association between arthritis, and age category(65 or over) of an individual.\n\n# Normality-tests\n\n-   Null: The sample data comes from a normally distributed population.\n-   Alternative: The sample data does not come from a normally distributed population\n\n# Investigation of assumptions\n\nIn this analysis, we are making the following assumptions about our data: - The data is normally distributed - The expected values in the contingency table for categorical variables are not less than 5 in each cell. - \\## Visual inspection using graphs\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlean_brfss |> \n  select(arthritis,bmi) |> \n  ggplot(aes(sample = bmi))+\n  geom_qq()+\n  geom_qq_line(colour = \"red\", linewidth = 1) +\n  facet_grid(~arthritis) +\n  theme_bw() \n```\n\n::: {.cell-output-display}\n![](stat_modelling_files/figure-html/Generating Q-Q plots-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbrfss_eliminated |> \n  ggplot(aes(x = bmi))+\n  geom_histogram(aes(y = after_stat(density), \n                     fill = ..count..))+\n  #geom_density(aes(y = after_stat(density)), color = \"red\", linewidth = 1) +\n  geom_vline(xintercept = mean(lean_brfss$bmi), \n             color = \"purple\", \n             linewidth = 0.8)+\n  geom_vline(xintercept = median(lean_brfss$bmi), \n             color = \"orange\", \n             linewidth = 0.8)+\n  facet_grid(~arthritis) +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stat_modelling_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\nThe graphical analysis shows that bmi variable is not normally distributed. Both the qq-plot and histograms show that data is skewed. For the qq plots, the points deviate upwards from the red line the for the arthritis variable indicating violations of normality. The histogram for the same shows that the mean and median is not equal, and hence skewed. We will attempt to transform the bmi variable by taking the log to base 10 of the bmi.\n\n## Data Transformation\n\nObservations from the visual inspection of the data, show that the bmi variable is not normally distributed, as the histograms and Q-Q plots have longer tails to the right, and data points deviating from red line respectively. Below, we are methods to transform the variable (bmi) using the three methods.\n\n### Log transformation\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlean_brfss |> \n  ggplot(aes(x = log(bmi)))+\n  geom_histogram(aes(y = after_stat(density), \n                     fill = ..count..))+\n  #geom_density(aes(y = after_stat(density)), color = \"red\", linewidth = 1) +\n  geom_vline(xintercept = mean(log(lean_brfss$bmi)), \n             color = \"purple\", linewidth = 0.8)+\n  geom_vline(xintercept = median(log(lean_brfss$bmi)), \n             color = \"orange\", linewidth = 0.8)+\n  facet_grid(~arthritis) +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stat_modelling_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\n### Square root transformation\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlean_brfss |> \n  ggplot(aes(x = sqrt(bmi)))+\n  geom_histogram(aes(y = after_stat(density), \n                     fill = ..count..))+\n  #geom_density(aes(y = after_stat(density)), color = \"red\", linewidth = 1) +\n  geom_vline(xintercept = mean(sqrt(lean_brfss$bmi)), \n             color = \"purple\", linewidth = 0.8)+\n  geom_vline(xintercept = median(sqrt(lean_brfss$bmi)), \n             color = \"orange\", linewidth = 0.8)+\n  facet_grid(~arthritis) +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stat_modelling_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\n### Square transformation\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlean_brfss |> \n  ggplot(aes(x = (bmi^2)))+\n  geom_histogram(aes(y = after_stat(density), \n                     fill = ..count..))+\n  #geom_density(aes(y = after_stat(density)), color = \"red\", linewidth = 1) +\n  geom_vline(xintercept = mean((lean_brfss$bmi^2)), \n             color = \"purple\", linewidth = 0.8)+\n  geom_vline(xintercept = median((lean_brfss$bmi^2)), \n             color = \"orange\", linewidth = 0.8)+\n  facet_grid(~arthritis) +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stat_modelling_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\nFrom the above outputs we can see that all methods of data transformation have not been able to result in normal distribution of bmi. Since graphic visualizations of tests are necessary but not sufficient we have further used the Shapiro test of significance below.\n\n## Test of signifcance\n\nUsing a sample of 4999 observations from the main dataset, we test for normality using the Shapiro Wilks test.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234) # for reproducibility\nbmi_sample<-lean_brfss |>\n  select(bmi) |> \n  drop_na(bmi) |> \n  sample_n(4999) \n\nbmi_sample |> \n  pull(bmi) |> \n  shapiro.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  pull(bmi_sample, bmi)\nW = 0.91633, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nThe test results from the test show that firstly, the test statistic of 0.69345 is far from 1, indicating the deviation from the mean. The p-value is significant, is extremely low showing that there is strong evidence to reject the null hypothesis, and conclude that data for bmi is not coming from a normally distributed population.\n\nAll the assumptions except for chi-square test of independence have not been met for both the graphics, and significance tests. Since parametric methods such as students t tests, anova require data to be normally distributed, we are going to use non-parametric methods to analyse the dataset even as these methods have less power.\n\n# Primary data analysis\n\n## Assessing associations\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsex_subt |> \n  table() |> \n  chisq.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  table(sex_subt)\nX-squared = 3016, df = 1, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nage_subt |> \n  table() |> \n  chisq.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  table(age_subt)\nX-squared = 27231, df = 1, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nactivity_subt |> \n  table() |> \n  chisq.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  table(activity_subt)\nX-squared = 4413, df = 1, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(bmi~arthritis,data=brfss_eliminated,conf.int=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  bmi by arthritis\nW = 1.5633e+10, p-value < 2.2e-16\nalternative hypothesis: true location shift is not equal to 0\n95 percent confidence interval:\n 1.489961 1.559952\nsample estimates:\ndifference in location \n              1.520008 \n```\n\n\n:::\n:::\n\n\n\n\n## Assessing relative risk (RR)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsex_subt |> \n  table() |> \n  epitools::epitab(method=\"riskratio\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$tab\n        arthritis\nSex        Yes        p0     No        p1 riskratio    lower    upper p.value\n  Female 71737 0.3652039 124693 0.6347961  1.000000       NA       NA      NA\n  Male   42144 0.2772066 109887 0.7227934  1.138623 1.133424 1.143845       0\n\n$measure\n[1] \"wald\"\n\n$conf.level\n[1] 0.95\n\n$pvalue\n[1] \"fisher.exact\"\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nage_subt |> \n  table() |> \n  epitools::epitab(method=\"riskratio\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$tab\n              arthritis\nage_65_or_over   Yes        p0     No        p1 riskratio    lower    upper\n           Yes 56240 0.5231093  51271 0.4768907  1.000000       NA       NA\n           No  57641 0.2392239 183309 0.7607761  1.595284 1.584712 1.605926\n              arthritis\nage_65_or_over p.value\n           Yes      NA\n           No        0\n\n$measure\n[1] \"wald\"\n\n$conf.level\n[1] 0.95\n\n$pvalue\n[1] \"fisher.exact\"\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nactivity_subt |> \n  table()|> \n  epitools::epitab(method=\"riskratio\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$tab\n                 arthritis\nphysical_activity   Yes        p0     No        p1 riskratio  lower    upper\n              No  36915 0.4173120  51544 0.5826880  1.000000     NA       NA\n              Yes 76966 0.2960208 183036 0.7039792  1.208158 1.2008 1.215561\n                 arthritis\nphysical_activity p.value\n              No       NA\n              Yes       0\n\n$measure\n[1] \"wald\"\n\n$conf.level\n[1] 0.95\n\n$pvalue\n[1] \"fisher.exact\"\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_data<-brfss_eliminated |> \n  select(arthritis,bmi,age_65_or_over,Sex,physical_activity)\n\nmodel_lr<-glm(arthritis~.,data = model_data,family = binomial(\"logit\"))\nsummary(model_lr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = arthritis ~ ., family = binomial(\"logit\"), data = model_data)\n\nCoefficients:\n                       Estimate Std. Error z value Pr(>|z|)    \n(Intercept)           1.2621793  0.0228869   55.15   <2e-16 ***\nbmi                  -0.0660347  0.0007623  -86.62   <2e-16 ***\nage_65_or_overNo      1.2707663  0.0079701  159.44   <2e-16 ***\nSexMale               0.4330701  0.0078421   55.22   <2e-16 ***\nphysical_activityYes  0.3712731  0.0085998   43.17   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 440383  on 348460  degrees of freedom\nResidual deviance: 400874  on 348456  degrees of freedom\nAIC: 400884\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_lr |> \n  tbl_regression(exponentiate = TRUE, conf.int = TRUE) |> \n  add_global_p() |> \n  bold_labels() |> \n  add_glance_table(include = c(nobs,BIC,AIC,logLik))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ebjqvveeby\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ebjqvveeby table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ebjqvveeby thead, #ebjqvveeby tbody, #ebjqvveeby tfoot, #ebjqvveeby tr, #ebjqvveeby td, #ebjqvveeby th {\n  border-style: none;\n}\n\n#ebjqvveeby p {\n  margin: 0;\n  padding: 0;\n}\n\n#ebjqvveeby .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ebjqvveeby .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ebjqvveeby .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ebjqvveeby .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ebjqvveeby .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ebjqvveeby .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ebjqvveeby .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ebjqvveeby .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ebjqvveeby .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ebjqvveeby .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ebjqvveeby .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ebjqvveeby .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ebjqvveeby .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ebjqvveeby .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ebjqvveeby .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ebjqvveeby .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ebjqvveeby .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ebjqvveeby .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ebjqvveeby .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ebjqvveeby .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ebjqvveeby .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ebjqvveeby .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ebjqvveeby .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ebjqvveeby .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ebjqvveeby .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ebjqvveeby .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ebjqvveeby .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ebjqvveeby .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ebjqvveeby .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ebjqvveeby .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ebjqvveeby .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ebjqvveeby .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ebjqvveeby .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ebjqvveeby .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ebjqvveeby .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ebjqvveeby .gt_left {\n  text-align: left;\n}\n\n#ebjqvveeby .gt_center {\n  text-align: center;\n}\n\n#ebjqvveeby .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ebjqvveeby .gt_font_normal {\n  font-weight: normal;\n}\n\n#ebjqvveeby .gt_font_bold {\n  font-weight: bold;\n}\n\n#ebjqvveeby .gt_font_italic {\n  font-style: italic;\n}\n\n#ebjqvveeby .gt_super {\n  font-size: 65%;\n}\n\n#ebjqvveeby .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ebjqvveeby .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ebjqvveeby .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ebjqvveeby .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ebjqvveeby .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ebjqvveeby .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ebjqvveeby .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ebjqvveeby .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ebjqvveeby div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">bmi</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.94</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.93, 0.94</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">age_65_or_over</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Yes</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    No</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">3.56</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">3.51, 3.62</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Sex</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.54</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1.52, 1.57</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">physical_activity</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    No</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Yes</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.45</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1.43, 1.47</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\">No. Obs.</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\">348,461</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">BIC</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">400,938</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">AIC</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">400,884</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Log-likelihood</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-200,437</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n# Using the finalfit package\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndependent <- \"arthritis\"\nexplanatory_multi <- c(\"bmi\",\"age_65_or_over\",\"Sex\",\"physical_activity\")\nmodel_data %>% \n  finalfit::or_plot(dependent, explanatory_multi,\n          breaks = c(0.5, 1, 2, 3, 4,5),\n          table_text_size = 3.5,\n          title_text_size = 16)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWaiting for profiling to be done...\nWaiting for profiling to be done...\nWaiting for profiling to be done...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 3 rows containing missing values or values outside the scale range\n(`geom_errorbarh()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stat_modelling_files/figure-html/OR and confidence intervals-1.png){width=672}\n:::\n:::\n\n\n\n\n# Interpretation\n\nThe results from both bivariate, and multivariate analysis present strong evidence of association between arthritis, and explanatory variables (sex, age, physical activity, and BMI):\n\n## 1. Sex, and Arthritis\n\n-   Chi-square test of indeoendence shows a statistically significant relationship between sex and arthritis (X-squared = 27231 = 3016, df = 1, p\\<0.001), indicating that arthritis prevalence is different in males and females.\n\n-   Risk Ratio: Males have a lower risk of arthritis comppared to females (RR = 0.86, 95% CI: 0.86-0.88, p\\<0.001). This means that the risk of arthritis in males is about 14% lower than in females.\n\n-   Logistic regression: Adjusted OR = 1.54 (95% CI: 1.52-1.57), p\\<0.001. This means that after adjusting for BMI, age, and physical activity, females have 54% higher odds of having arthritis compared to males. The 95% confidence interval does not include 1, and extremely narrow indicating that the estimate is quite precise.\n\n## 2. Age and Arthritis\n\n-   Chi-square test results show that there is a strong evidence of association between age (65and over) and arthritis (X-squared = 27231, df = 1, p \\< 0.001). The p-value is less than 0.05, we therefore reject the null hypothesis, and conclude that the association between age and arthritis is not by chance.\n\n-   Risk Ratio: Individuals aged 65 or older have a relative risk of 2.18 (95% CI: 2.15-2.20, p \\< 0.001), suggesting that they are more than twice as likely to have arthritis compared to individuals below 65.\n\nLogistic regression: Adjusted OR = 3.56 (95% CI: 3.51-3.62, p \\< 0.001), showing that being 65 or older increases the odds of having arthritis by 3.5 times after adjusting for other variables. Again, the low p - value (less than 0.05) as well as the narrow confidence interval shows that the estimate is both significant and quite precise.\n\n## 3. Physical Activity and Arthritis\n\n-   Chi-square test: The association between physical activity, and arthritis is significant (X-squared = 4413, df = 1, p \\< 0.001). Given the small p value (less than 0.05), we reject the null hypothesis, and conclude that the difference is unlikely to be due to random variation alone.\n\n-   Risk Ratio: Individuals who are physically inactive have higher risk of developing athritis (RR = 1.21, 95% CI: 1.20-1.22, p \\< 0.001), showing that there is a 21% increased risk compared to physically active individuals.\n\n-   Logistic regression: With Adjusted OR = 1.45 (95% CI: 1.43-1.47, p \\< 0.001). This means that physical inactivity increases the odds of arthritis by 45% holding other variables constant.The p value is less than 0.05 (given alpha level), and therefore significant. Note that the confidence interval is narrow, and does not include 1 making the estimate so certain and precise.\n\n## 4. BMI and Arthritis\n\n-   Wilcoxon Rank-Sum Test (Mann-Whitney U Test): Since BMI is numeric and skewed, this test is ideal because it is non-parametric. The p - value is less than 0.05 (0.001), and the confidence interval is narrow(W-Statistic 1.52, 95% CI:1.49-1.56, p \\< 0.001) and does not include 0, we reject the null hypothesis, and conclude that individuals with arthritis tend to have higher BMI than those without arthritis.\n\n-   Logistic regression: The adjusted OR = 0.94 (95% CI: 0.93-0.94, p \\< 0.001) suggests that there is a 6% decrease in the odds of arthritis for every unit of BMI gained. Even as this is significant the result is inverse relationship could suggest possible confounding in our model.\n\n#### \n\n# Machine Learning\n\nLoading \\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\\>\n",
    "supporting": [
      "stat_modelling_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}