{
  "hash": "93c321d6664d30aae152f1fd3f4ac20b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"MLearning\"\nformat: html\neditor: visual\neditor_options: \n  chunk_output_type: console\n---\n\n## Project Summary\n\n**Goal:** Predict diabetes status from demographic and clinical risk factors using the NHANES dataset.\n\n**Data:** National Health and Nutrition Examination Survey collected in the US. Variables include age, BMI, direct cholesterol, marital status, and gender.\n\n**Models:** Logistic Regression and Random Forest (tidymodels framework).\n\n**Key Finding:** Random Forest outperformed logistic regression across all metrics. Sensitivity improved from 4% (logistic regression) to 34% (Random Forest), with ROC-AUC of 0.89. Both models struggled with the minority class due to class imbalance.\n\n**Tools:** R, tidymodels, ranger, ggstatsplot, cowplot, gtsummary\n\n## Introduction\n\nIn this project we will use the NHANES dataset to predict diabetes given the available risk factors. The National Health ans Nutrition Survey is a a program in the US designed to assess the health and nutritional status pf adults, and children in the US. The data includes demographic, socio-economic, dietary, and health-related information.\n\n### Loading packages including the dataset.\n\n\n\n### Data Preparation\n\nWe are going to save the dataset into the nhanes_df object to maintain the original dataset intact.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnhanes_df<-NHANES |> \n  select(Diabetes,DirectChol,BMI,MaritalStatus,Age,Gender) |>\n  drop_na() |> # Assuming variables are missing completely at Random\n  clean_names()\n\n# Changing the levels for appropriate analysis\nnhanes_df<-nhanes_df |> \n  mutate(diabetes=factor(diabetes, \n                         levels = c(\"Yes\", \"No\"))) |> \n           glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 6,786\nColumns: 6\n$ diabetes       <fct> No, No, No, No, No, No, No, No, No, No, No, No, No, No,…\n$ direct_chol    <dbl> 1.29, 1.29, 1.29, 1.16, 2.12, 2.12, 2.12, 0.67, 0.96, 1…\n$ bmi            <dbl> 32.22, 32.22, 32.22, 30.57, 27.24, 27.24, 27.24, 23.67,…\n$ marital_status <fct> Married, Married, Married, LivePartner, Married, Marrie…\n$ age            <int> 34, 34, 34, 49, 45, 45, 45, 66, 58, 54, 58, 50, 33, 60,…\n$ gender         <fct> male, male, male, female, female, female, female, male,…\n```\n\n\n:::\n:::\n\n\n## Train/Test Split\n\nIn the code below, we are splitting our data into training and testing sets (0.8, 0.2) and stratify by the diabetes to preserve class proportions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123) #For reproducubility\nml_split<-initial_split(nhanes_df,\n                        prop = 0.8,\n                        strata = diabetes)\n\nml_training<-ml_split |> \n  training()\n\nml_test<-ml_split |>\n  testing()\n```\n:::\n\n\n## Logistic Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlr_model<-logistic_reg() |> \n  set_engine(\"glm\") |> \n  set_mode(\"classification\") \n```\n:::\n\n\n### Correlation Check\n\n\n::: {.cell}\n\n```{.r .cell-code}\nml_training |> \n  select_if(is.numeric) |> \n  ggcorrmat(colors = c(\"#B2182B\", \"White\", \"#4D4D4D\"),\n            title = \"Colleration Matrix\"\n            )\n```\n\n::: {.cell-output-display}\n![](nhanes_ml_project_files/figure-html/Checking for Correlated predictors-1.png){width=672}\n:::\n:::\n\n\nUsing the hypothetical threshold of 0.8, we can conclude that the predictors are not collerated. In the code below, we are going to fit both models using the fit function. After which we are going to collect and combine predictions, and load them.\n\nIn the code below we are going to specify a recipe object after which we will add steps for engineering our features (feature engineering). The steps are to preprocess the data into a form that will allegedly improve our analysis.\n\n### Workflow and Fit\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nlr_recipe<-recipe(diabetes~.,data = ml_training) |>\n  step_log(all_numeric()) |> \n  step_normalize(all_numeric()) |> #Centering and scaling\n  step_dummy(all_nominal(), -all_outcomes())\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlr_worflow<-workflow() |> \n  add_model(lr_model) |> \n  add_recipe(lr_recipe)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nlr_worflow_fit<-lr_worflow |> \n  last_fit(split = ml_split)\n\nlr_worflow_fit |> \n  collect_metrics()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  .metric     .estimator .estimate .config             \n  <chr>       <chr>          <dbl> <chr>               \n1 accuracy    binary        0.909  Preprocessor1_Model1\n2 roc_auc     binary        0.790  Preprocessor1_Model1\n3 brier_class binary        0.0743 Preprocessor1_Model1\n```\n\n\n:::\n\n```{.r .cell-code}\nlr_resultss<-lr_worflow_fit |> \n  collect_predictions()\n\nlr_resultss\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,358 × 7\n   .pred_class .pred_Yes .pred_No id                .row diabetes .config       \n   <fct>           <dbl>    <dbl> <chr>            <int> <fct>    <chr>         \n 1 No             0.0774    0.923 train/test split     4 No       Preprocessor1…\n 2 No             0.0941    0.906 train/test split    10 No       Preprocessor1…\n 3 No             0.103     0.897 train/test split    11 No       Preprocessor1…\n 4 No             0.101     0.899 train/test split    12 No       Preprocessor1…\n 5 No             0.112     0.888 train/test split    14 No       Preprocessor1…\n 6 No             0.0235    0.976 train/test split    15 No       Preprocessor1…\n 7 No             0.207     0.793 train/test split    19 No       Preprocessor1…\n 8 No             0.131     0.869 train/test split    22 Yes      Preprocessor1…\n 9 No             0.122     0.878 train/test split    24 Yes      Preprocessor1…\n10 No             0.0877    0.912 train/test split    28 No       Preprocessor1…\n# ℹ 1,348 more rows\n```\n\n\n:::\n:::\n\n\n## Logistic Regression Results\n\n### Confusion Matrix\n\nIn this section we are going to visualize the model results. We will start with the **confusion matrix**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nlr_resultss |> \n  conf_mat(truth = diabetes,\n           estimate = .pred_class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Truth\nPrediction  Yes   No\n       Yes    4    8\n       No   116 1230\n```\n\n\n:::\n:::\n\n\n-   The logistic regression correctly classifies 1,237 out of 1,358 individuals (91%). 116 false negatives and 8 false positives.\n\n    ### Performance Metrics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(112)\nlr_metric<-metric_set(sens,accuracy, yardstick::spec)\n\n\n\nlr_resultss |> \n  lr_metric(truth = diabetes, \n            estimate = .pred_class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  .metric  .estimator .estimate\n  <chr>    <chr>          <dbl>\n1 sens     binary        0.0333\n2 accuracy binary        0.909 \n3 spec     binary        0.994 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nlr_resultss |>\n  roc_curve(truth = diabetes,.pred_Yes) |>\n  autoplot()\n```\n\n::: {.cell-output-display}\n![](nhanes_ml_project_files/figure-html/Model metrics-1.png){width=672}\n:::\n\n```{.r .cell-code}\nroc_auc(lr_resultss, truth = diabetes, .pred_Yes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 roc_auc binary         0.790\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nheatmap_lr<-conf_mat(lr_resultss, truth = diabetes, estimate = .pred_class) |> \n  autoplot(type = \"heatmap\")\n\n\nmosaic_lr<-conf_mat(lr_resultss, truth = diabetes, estimate = .pred_class) |> \n  autoplot(type = \"mosaic\")\n\ncowplot::plot_grid(mosaic_lr,heatmap_lr)\n```\n\n::: {.cell-output-display}\n![](nhanes_ml_project_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThe 91.1% accuracy is misleading. The model predicts negative cases well (high specificity) but identifies only 4 out of 120 positive cases. Accuracy alone is not a useful metric here due to class imbalance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nroc_auc(lr_resultss,truth = diabetes,.pred_Yes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 roc_auc binary         0.790\n```\n\n\n:::\n\n```{.r .cell-code}\nlr_roc_plot<-lr_resultss |> \n  roc_curve(truth = diabetes, .pred_Yes) |> \n  autoplot()\n  \nlr_roc_plot\n```\n\n::: {.cell-output-display}\n![](nhanes_ml_project_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n### Random Forest\n\nLogistic regression failed to correctly identify positive cases. Random Forest offers more flexibility for nonlinear relationships and imbalanced data.\n\n### Model Specification\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrf<-rand_forest() |> \n  set_args(mtry = 9) |> \n  set_engine(\"ranger\", importance = \"impurity\") |> \n  set_mode(\"classification\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nrf_recipe<-recipe(diabetes~.,data = ml_training) |> \n  step_log(all_numeric()) |> \n  step_normalize(all_numeric()) |> \n  step_dummy(all_nominal(),-all_outcomes())\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrf_workflow<-workflow() |> \n  add_model(rf) |> \n  add_recipe(rf_recipe)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nrf_wrkflw_fit<-rf_workflow |> \n  tune::last_fit(split = ml_split)\n\nrf_wrkflw_fit |> \n  collect_metrics()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  .metric     .estimator .estimate .config             \n  <chr>       <chr>          <dbl> <chr>               \n1 accuracy    binary        0.935  Preprocessor1_Model1\n2 roc_auc     binary        0.896  Preprocessor1_Model1\n3 brier_class binary        0.0551 Preprocessor1_Model1\n```\n\n\n:::\n\n```{.r .cell-code}\nrf_results<-rf_wrkflw_fit |> \n  collect_predictions()\n```\n:::\n\n\n### Random Forest Results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nmosaic_rf<-rf_results |> \n  conf_mat(truth = diabetes,.pred_class) |> \n  autoplot(type = \"mosaic\")\n\nheatmap_rf<-rf_results |> \n  conf_mat(truth = diabetes,.pred_class) |>\n  autoplot(type = \"heatmap\")\n  \ncowplot::plot_grid(heatmap_rf,mosaic_rf)\n```\n\n::: {.cell-output-display}\n![](nhanes_ml_project_files/figure-html/Conf Matrix-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nrf_metrics<-metric_set(yardstick::sens, yardstick::spec, yardstick::accuracy)\n\n\nlr_resultss |> \n  rf_metrics(truth = diabetes, \n            estimate = .pred_class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  .metric  .estimator .estimate\n  <chr>    <chr>          <dbl>\n1 sens     binary        0.0333\n2 spec     binary        0.994 \n3 accuracy binary        0.909 \n```\n\n\n:::\n\n```{.r .cell-code}\nrf_results |> \n  rf_metrics(truth = diabetes, estimate = .pred_class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  .metric  .estimator .estimate\n  <chr>    <chr>          <dbl>\n1 sens     binary         0.35 \n2 spec     binary         0.992\n3 accuracy binary         0.935\n```\n\n\n:::\n\n```{.r .cell-code}\nrf_results |> \n  roc_auc(truth = diabetes,.pred_Yes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 roc_auc binary         0.896\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrf_roc_plot<-rf_results |> \n  roc_curve(truth = diabetes,.pred_Yes) |> \n  autoplot()\n```\n:::\n\n\n### Model comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncowplot::plot_grid(rf_roc_plot, lr_roc_plot,labels = c(\"Random Forest\", \"Logistic Regression\"),label_size = 12)\n```\n\n::: {.cell-output-display}\n![](nhanes_ml_project_files/figure-html/Model comparison-1.png){width=672}\n:::\n:::\n\n\nRandom Forest outperforms logistic regression on all metrics:\n\n| Metric      | Logistic Regression | Random Forest |\n|-------------|---------------------|---------------|\n| Accuracy    | 0.91                | 0.93          |\n| Sensitivity | 0.04                | 0.35          |\n| Specificity | 0.99                | 0.99          |\n| ROC-AUC     | 0.83                | 0.89          |\n\n: The Random Forest improves sensitivity from 4% to 34%. The model still misses 64% of positive cases due to class imbalance.\n\n### Prediction Example (Use case)\n\n\n::: {.cell}\n\n```{.r .cell-code}\npatient1<-tribble(~age,~bmi,~direct_chol,~marital_status,~gender,\n                  40,27.3,1.5,\"Divorced\",\"female\")\n\nrf_pred<-rf_wrkflw_fit |> \n  extract_workflow()\n\npredict(rf_pred, new_data = patient1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred_class\n  <fct>      \n1 No         \n```\n\n\n:::\n:::\n\n\nThe model predicts this patient does not have diabetes. Given the model's high specificity, negative predictions are reliable.\n\n## Limitations and Next Steps\n\nThis analysis skipped hyperparameter tuning (k-fold cross validation) and did not address class imbalance through oversampling (SMOTE) or threshold adjustment. These are the clear next steps for improving sensitivity on the minority class.\n",
    "supporting": [
      "nhanes_ml_project_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}