project:
  type: website
  output-dir: docs

website:
  title: "David Mwale - Data Science Portfolio"
  site-url: https://mwaledaveed99.github.io/mwaledaveed99/
  description: "A portfolio showcasing David Mwale's R projects in data cleaning, visualization, statistical modeling, and machine learning."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      #- href: projects.qmd
       # text: Projects
      - href: cleaning.qmd
        text: Data Cleaning
      - href: stat_modelling.qmd
        text: Statistical Modelling
      - href: nhanes_ml_project.qmd
        text: Machine Learning
  page-footer:
    center: "**© 2025 David Mwale**"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

execute:
  freeze: auto


