project:
  type: website
  output-dir: docs

website:
  title: "Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: portfolio.qmd
        text: Portfolio

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



