project:
  type: website
  output-dir: docs

website:
  title: "David Mwale"
  site-url: https://mwaledaveed99.github.io/mwaledaveed99/
  description: "Data Science Portfolio | MSc Data Science, University of Edinburgh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu:
          - href: cleaning.qmd
            text: Data Cleaning
          - href: stat_modelling.qmd
            text: Statistical Modelling
          - href: nhanes_ml_project.qmd
            text: Machine Learning
      - text: Dashboards
        menu:
          - href: https://ztv548-david-mwale.shinyapps.io/shiny_app/
            text: Shiny Dashboard
    right:
      - icon: github
        href: https://github.com/mwaledaveed99
      - icon: linkedin
        href: https://www.linkedin.com/in/david-mwale-b47490103

  page-footer:
    center: "© 2025 David Mwale. Built with Quarto."

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

execute:
  freeze: auto




